

- name: Install NFS Server Packages
  become: true
  apt:
    pkg: nfs-kernel-server
    state: present
    update_cache: "yes"

- name: SSH Password Authentication
  become: yes
  lineinfile:
    path: /etc/exports
    state: present
    line: "{{ item }}"
  loop: "{{ nfs_shares }}"

- name: Export NFS Shares
  become: yes
  shell: exportfs -ra
