# Maintainer: Kevin Jayne
options:
  ssh_password: false
  install:
    ohmyzsh: true

apt:
  - autojump
  - ctags
  - coreutils
  - curl 
  - git
  - htop
  - jq
  - neovim
  - steamlink
  - terminator
  - wakeonlan
  - wget
  - zsh

directories:
  - ~/.config/nvim
  - ~/.config/terminator
  - ~/.history

files:
  - { src: '.zshrc', dest: '~/.zshrc'}
  - { src: '.vimrc', dest: '~/.vimrc'}
  - { src: '.bashrc', dest: '~/.bashrc'}
  - { src: 'init.vim', dest: '~/.config/nvim/init.vim'}
  - { src: 'terminator.config', dest: '~/.config/terminator/config'}

# Order Matters!
autostart:
  - "@lxpanel --profile LXDE-pi"
  - "@pcmanfm --desktop --profile LXDE-pi"
  - "@xscreensaver -no-splash"
  - wakeonlan -i 10.0.0.255 a8:5e:45:e3:e2:2e
  - steamlink
