# Maintainer: Kevin Jayne
options:
  install:
    ohmyzsh: true

apt:
  - autojump
  - ctags
  - coreutils
  - curl 
  - git
  - htop
  - jq
  - neovim
  - steamlink
  - terminator
  - wakeonlan
  - wget
  - zsh

directories:
  - ~/.config/nvim
  - ~/.config/terminator
  - ~/.history

files:
  - { src: '.zshrc', dest: '~/.zshrc'}
  - { src: '.vimrc', dest: '~/.vimrc'}
  - { src: '.bashrc', dest: '~/.bashrc'}
  - { src: 'init.vim', dest: '~/.config/nvim/init.vim'}
  - { src: 'terminator.config', dest: '~/.config/terminator/config'}

# Order Matters!
autostart:
  - wakeonlan -i 10.0.0.255 bc:ae:c5:50:ef:49
  - steamlink
