# Maintainer: Kevin Jayne
options:
  ssh:
    PasswordAuthentication: "no"
  install:
    ohmyzsh: yes

apt:
  - autojump
  - ctags
  - coreutils
  - curl 
  - git
  - htop
  - jq
  - neovim
  - steamlink
  - terminator
  - wakeonlan
  - wget
  - zsh

directories:
  - ~/.config/nvim
  - ~/.config/terminator
  - ~/.history

files:
  - { src: '.zshrc', dest: '~/.zshrc'}
  - { src: '.vimrc', dest: '~/.vimrc'}
  - { src: '.bashrc', dest: '~/.bashrc'}
  - { src: 'init.vim', dest: '~/.config/nvim/init.vim'}
  - { src: 'terminator.config', dest: '~/.config/terminator/config'}

# Order Matters!
autostart:
  - "@lxpanel --profile LXDE-pi"
  - "@pcmanfm --desktop --profile LXDE-pi"
  - "@xscreensaver -no-splash"
  # - wakeonlan -i 10.0.0.255 a8:5e:45:e3:e2:2e
  # - steamlink

k3s:
  tmpfile: /tmp/k3s.sh
  url: https://get.k3s.io
  nodetoken: /var/lib/rancher/k3s/server/node-token
  kubeconfig: /etc/rancher/k3s/k3s.yaml
  local_kubeconfig: ~/.kube/k3sconfig
  static:
    router: "10.0.0.1"
    dns: "10.0.0.1 1.1.1.1 8.8.8.8"

fstab:
  - {dir: /home/pi/Movies, mount: "//GAMEBOX/Movies  /home/pi/Movies  cifs uid=nobody,iocharset=utf8,noperm 0 0"}
