# Maintainer: Kevin Jayne
ssh:
  PasswordAuthentication: "no"
  public_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+sFtH2o+FxlTDAuPGvBIFrOqsLOxNmWFv4F51HrcbgMZ4LqwUhSi5Hx6o9vgF9sSGJhNaOUjmCbj6DsU4Cs9cHgCDeiYbOwjucLIc1XSjc3ON+geS2PLpif48hEyHwhIhkZWllUXTOX4z9qbfsIpAKAdBKumqj5yIIB9ZOAqWukFTFPSlFTZH5Ps1SWI+CkrJvD9DlmrFh6jg4Yakvrr+p3/rHyw5xL6xwq3n5rxxBepO5NnSpmNOW3MYMWnXGWigXnpWum9huBpeEOGgHXq1viCsw7XUOr4VCSJjAacbHaBuBCavUomxyQUfXV1nYk97z9CMBsy9UBnDCOTzyokp kevinjayne@Kevins-MacBook-Pro.local

install_ohmyzsh: yes

apt:
  - autojump
  - ctags
  - coreutils
  - curl 
  - git
  - htop
  - jq
  - neovim
  - nfs-common
  - nfs-kernel-server
  - steamlink
  - terminator
  - wakeonlan
  - wget
  - zsh

directories:
  - ~/.config/nvim
  - ~/.config/terminator
  - ~/.history

files:
  - { src: '.zshrc', dest: '~/.zshrc'}
  - { src: '.vimrc', dest: '~/.vimrc'}
  - { src: '.bashrc', dest: '~/.bashrc'}
  - { src: 'init.vim', dest: '~/.config/nvim/init.vim'}
  - { src: 'terminator.config', dest: '~/.config/terminator/config'}

# Order Matters!
autostart:
  - "@lxpanel --profile LXDE-pi"
  - "@pcmanfm --desktop --profile LXDE-pi"
  - "@xscreensaver -no-splash"
  # - wakeonlan -i 10.0.0.255 a8:5e:45:e3:e2:2e
  # - steamlink

k3s:
  tmpfile: /tmp/k3s.sh
  url: https://get.k3s.io
  nodetoken: /var/lib/rancher/k3s/server/node-token
  kubeconfig: /etc/rancher/k3s/k3s.yaml
  local_kubeconfig: ~/.kube/k3sconfig
  static:
    router: "10.0.0.1"
    dns: "10.0.0.1 1.1.1.1 8.8.8.8"

