# Maintainer: Kevin Jayne

install_ohmyzsh: yes

ssh:
  PasswordAuthentication: "yes"

apple:
  brew:
    cask:
      - docker
    packages:
      - curl
      - git
      - hddtemp
      - htop
      - jq
      - neovim
      # - nfs-common
      # - steamlink
      - wakeonlan
      - wget
      - zsh

apt:
  - autojump
  - ctags
  - coreutils
  - curl
  - git
  - hddtemp
  - htop
  - jq
  - lm-sensors
  - neovim
  - nfs-common
  - steamlink
  - terminator
  - wakeonlan
  - wget
  - zsh

directories:
  - ~/.config/nvim
  - ~/.config/terminator
  - ~/.history

config_files:
  - { src: ".zshrc", dest: "~/.zshrc" }
  - { src: ".vimrc", dest: "~/.vimrc" }
  - { src: ".bashrc", dest: "~/.bashrc" }
  - { src: "init.vim", dest: "~/.config/nvim/init.vim" }
  - { src: "terminator.config", dest: "~/.config/terminator/config" }

# Order Matters!
autostart:
  - "@lxpanel --profile LXDE-pi"
  - "@pcmanfm --desktop --profile LXDE-pi"
  - "@xscreensaver -no-splash"
  # - wakeonlan -i 10.0.0.255 a8:5e:45:e3:e2:2e
  # - steamlink

# Lightweight Kubernetes: https://github.com/k3s-io/k3s/releases/
k3s:
  tmpfile: /tmp/k3s.sh
  url: https://get.k3s.io
  nodetoken: /var/lib/rancher/k3s/server/node-token
  kubeconfig: /etc/rancher/k3s/k3s.yaml
  adminIP: 10.0.0.10
  args: "--no-deploy servicelb --no-deploy traefik"
  local_kubeconfig: ~/.kube/k3sconfig
  static:
    router: "10.0.0.1"
    dns: "10.0.0.1 1.1.1.1 8.8.8.8"
