# K3sAdmin Vars

fs_mounts:
  - {
    path: /mnt/ssd/movies,
    src: "UUID=0CB81103B810ED48",
    fstype: ntfs,
    opts: "defaults,nobootwait,nofail,errors=remount-ro",
  }
  - {
    path: /mnt/ssd/series,
    src: "UUID=56885E3A885E18B7",
    fstype: ntfs,
    opts: "defaults,nobootwait,nofail,errors=remount-ro",
  }
  - {
    path: /mnt/ssd/pny250,
    src: "UUID=1DAC99F73EFA9CB8",
    fstype: ntfs,
    opts: "defaults,nobootwait,nofail,errors=remount-ro",
  }
  - {
    path: /mnt/hdd/tera,
    src: "UUID=D4504CF8504CE33A",
    fstype: ntfs,
    opts: "defaults,nobootwait,nofail,errors=remount-ro"
  }

nfs_shares:
  - /mnt/ssd/movies *(rw,no_root_squash,insecure,async,no_subtree_check,anonuid=1000,anongid=1000)
  - /mnt/ssd/series *(rw,no_root_squash,insecure,async,no_subtree_check,anonuid=1000,anongid=1000)
  - /mnt/ssd/pny250 *(rw,no_root_squash,insecure,async,no_subtree_check,anonuid=1000,anongid=1000)
  - /mnt/hdd/tera *(rw,no_root_squash,insecure,async,no_subtree_check,anonuid=1000,anongid=1000)
