
install_k3s: true 

# fs_mounts:
  # - {path: /path/to/mount/point, src: "UUID={YOUR-UID}", fstype: {file-system-type},   opts: "defaults,nobootwait,nofail,errors=remount-ro"}

nfs_mounts:
  - {path: /mnt/hdd/str, src: "pi-master.local:/mnt/hdd/str", fstype: nfs,  opts: rw}
  - {path: /mnt/hdd/media, src: "pi-master.local:/mnt/hdd/media", fstype: nfs,  opts: rw}
  # - {path: /home/pi/Movies, src: "//GAMEBOX/Movies", fstype:   cifs,  opts: "uid=nobody,iocharset=utf8,noperm 0 0"}
