# K3sPi group variables
user: admin
ssh_keygen: true

zsh:
  install: true
  ohmyzsh: true
  chsh: true

apt:
  - autojump
  - curl
  - git
  - htop
  - jq
  - neovim
  - nfs-common
  - tree
  - wget
  - zsh

directories:
  - ~/.config/nvim
  - ~/.history
  - ~/.kube

config_files:
  - { src: ".zshrc", dest: "~/.zshrc" }
  - { src: ".vimrc", dest: "~/.vimrc" }
  - { src: ".bashrc", dest: "~/.bashrc" }
  - { src: "init.vim", dest: "~/.config/nvim/init.vim" }

network_manager:
  connections:
    - name: "Wired connection 1"
      interface_name: "eth0"
    - name: "preconfigured"
      interface_name: "wlan0"
  method: "manual"
  gateway: "10.0.0.1"
  dns:
    - "10.0.0.1"
    - "1.1.1.1"
    - "8.8.8.8"
    - "9.9.9.9"

k3s: # Lightweight Kubernetes: https://github.com/k3s-io/k3s/releases/
  tmpfile: /tmp/k3s.sh
  url: https://get.k3s.io
  nodetoken: /var/lib/rancher/k3s/server/node-token
  kubeconfig: /etc/rancher/k3s/k3s.yaml
  local_kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/k3sconfig"
  args:
    - --write-kubeconfig-mode 644
    - --write-kubeconfig ~/.kube/k3sconfig
    - --disable=traefik
    - --disable=servicelb
    - --prefer-bundled-bin
