install_ohmyzsh: yes

ssh:
  user: admin
  PasswordAuthentication: "yes"

apt:
  - autojump
  - curl
  - git
  - golang-go
  - htop
  - jq
  - libasound2-dev
  - neovim
  - tree
  - wget
  - zsh

directories:
  - ~/.config/nvim
  - ~/.history
  - ~/.go

config_files:
  - { src: ".zshrc", dest: "~/.zshrc" }
  - { src: ".vimrc", dest: "~/.vimrc" }
  - { src: ".bashrc", dest: "~/.bashrc" }
  - { src: "init.vim", dest: "~/.config/nvim/init.vim" }

repos:
  local_dir: ~/git
  sources:
    - { src: 'git@github.com:seemywingz/ponder.git', dest: 'ponder'}