# vim:ft=ansible
- name: Create Config Directories on Pi
  file: 
    path: "{{item}}"
    state: directory
  with_items:
   - "{{ dotfiles.directories }}"

- name: Copy Dotfiles to Pi
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  with_items:
    - "{{ dotfiles.sources }}"

- name: Install Oh My ZSH
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh