# Default values for plex.

replicaCount: 1

image:
  repository: linuxserver/plex
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext: {}

# Plex claim token from https://plex.tv/claim
claimToken: "claim-9EFqgBysZ4-_wkq4b1iX"

# Set the timezone of the plex server
timezone: America/New_York

plexPort: "32400"

service:
  type: ClusterIP
  port: 32400
  targetPort: 32400
  protocol: TCP

ingress:
  enabled: true
  className: "nginx"
  annotations:
    { cert-manager.io/cluster-issuer: "cloudlfare-letsencrypt-production" }
  hosts:
    - host: plex.livingroom.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: plex.livingroom.cloud-tls
      hosts:
        - plex.livingroom.cloud

persistence:
  movies:
    storageClass: "ssd-movies"
    size: 100Gi
    accessMode: ReadWriteMany
  series:
    storageClass: "ssd-series"
    size: 100Gi
    accessMode: ReadWriteMany
  config:
    storageClass: "ssd-pny250-1"
    size: 1Gi
    accessMode: ReadWriteMany

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
