# Default values for test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# helm upgrade --install nginx-test chart --values values.yaml --namespace test
# helm upgrade --install nginx-demo services/demo/chart --values services/demo/values.yaml --namespace demo

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# podAnnotations: 
#   ad.datadoghq.com/nginx-test.check_names: '["ngidnx-test"]'
#   ad.datadoghq.com/nginx-test.init_configs: '[{}]'
#   ad.datadoghq.com/nginx-test.instances:  |
#       [
#         {
#           "host": "%%host%%",
#           "port":"6379",
#           "password":"%%env_REDIS_PASSWORD%%"
#         }
#       ]
#   ad.datadoghq.com/nginx-test.logs: '[{"source":"nginx-test","service":"nginx-test"}]'

image:
  repository: nginx
  pullPolicy: IfNotPresent


serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: 

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/ssl-redirect: "false",
    cert-manager.io/cluster-issuer: "letsencrypt-prod",
  }
  hosts:
    - host: demo.livingroom.cloud
      http:
      paths: 
        - /
  tls: 
    - secretName: demo-livingroom-cloud-tls
      hosts:
        - demo.livingroom.cloud

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
