# vim:ft=ansible

- name: Update Swap File Size in /etc/dphys-swapfile to {{ swapsize }}
  when: swapsize is defined
  become: true
  lineinfile:
    path: /etc/dphys-swapfile
    regexp: '^CONF_SWAPSIZE='
    line: 'CONF_SWAPSIZE={{ swapsize }}'
  notify: Restart dphys-swapfile
  
- name: Update /etc/fstab
  become: true
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: mounted
  loop: "{{ fs_mounts }}"
