# vim:ft=ansible

- name: Mount Devices to Local Filesystem
  become: true
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: mounted
  loop: "{{ fs_mounts }}"
