# vim:ft=ansible
- name: Create Directories on Pi
  file: 
    path: "{{item}}"
    state: directory
  with_items:
   - "{{ directories }}"

- name: Copy Files to Pi
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  with_items:
    - "{{ files }}"

- name: Install Oh My ZSH
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
  when: install_ohmyzsh|bool

- name: SSH Password Authentication
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '.*PasswordAuthentication (yes|no)'
    line: "PasswordAuthentication {{ ssh.PasswordAuthentication }}"
  notify: Restart SSH Service
