apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "plex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plex.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plex.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: plex
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /identity
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /identity
              port: {{ .Values.service.port }}
            initialDelaySeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: TZ
              value: "{{ .Values.timezone }}"
            # TODO: move this to a secret?
            - name: PLEX_CLAIM
              value: "{{ .Values.claimToken }}"
            # kube-plex env vars
            # - name: PMS_INTERNAL_ADDRESS
            #   value: http://{{ template "plex.fullname" . }}:32400
            - name: PMS_IMAGE
              value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: plex-movies
              mountPath: /data/Movies
            - name: plex-series
              mountPath: "/data/Series"
            - name: plex-config
              mountPath: /config
      volumes:
      - name: plex-movies
        persistentVolumeClaim:
          claimName: "{{- template "plex.fullname" . }}-movies"
      - name: plex-series
        persistentVolumeClaim:
          claimName: "{{- template "plex.fullname" . }}-series"
      - name: plex-config
        persistentVolumeClaim:
          claimName: "{{- template "plex.fullname" . }}-config"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
