
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "plex.fullname" . }}-config
  labels:
    app: {{ template "plex.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: config
spec:
  accessModes:
  - {{ .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
  storageClassName: {{ .Values.persistence.config.storageClass | quote }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "plex.fullname" . }}-movies
  labels:
    app: {{ template "plex.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: movies
spec:
  accessModes:
  - {{ .Values.persistence.movies.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.movies.size | quote }}
  storageClassName: {{ .Values.persistence.movies.storageClass | quote }}
---

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "plex.fullname" . }}-series
  labels:
    app: {{ template "plex.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: series
spec:
  accessModes:
  - {{ .Values.persistence.series.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.series.size | quote }}
  storageClassName: {{ .Values.persistence.series.storageClass | quote }}
---
