
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "plex.fullname" . }}-config
  labels:
    app: {{ template "plex.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: config
spec:
  accessModes:
  - {{ .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
  storageClassName: {{ .Values.persistence.config.storageClass | quote }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "plex.fullname" . }}-data
  labels:
    app: {{ template "plex.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: data
spec:
  accessModes:
  - {{ .Values.persistence.data.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
---
