# EMN DevOps initializer

- name: Provision Raspberry Pi Entertainment Consoles
  hosts: raspberries
  gather_facts: true
  tasks:

    - import_role:
        name: apt
      tags: [ 'init', 'apt' ]
  
    - import_role:
        name: config
      tags: [ 'init', 'config' ]
  
    - import_role:
        name: autostart
      tags: [ 'init', 'autostart' ]

    - import_role:
        name: fs
      tags: [ 'init', 'fs' ]
      when: fs_mounts is defined
    
    - import_role:
        name: nfs
      tags: [ 'init', 'nfs' ]
      when: nfs_shares is defined or nfs_mounts is defined
  
    - import_role:
        name: k3s
      tags: [ 'init', 'k3s' ]
      when: install_k3s|bool
  
  handlers:
     - import_tasks: ../handlers/main.yml

