# EMN DevOps initializer

- name: Provision Raspberry Pi Entertainmet Consoles
  hosts: raspberries
  gather_facts: true
  roles:
    - { role: cli, tags: [ 'init', 'cli' ]  }
    - { role: dotfiles, tags: [ 'init', 'dotfiles' ]  }
    - { role: services, tags: [ 'init', 'services' ]  }