# EMN DevOps initializer

- name: Provision Raspberry Pi Consoles
  hosts: pi
  gather_facts: true
  tasks:

    - import_role:
        name: apt
      tags: [ 'init', 'apt' ]
  
    - import_role:
        name: config
      tags: [ 'init', 'config' ]
    
    - import_role:
        name: repos
      tags: [ 'init', 'repos' ]
  
  handlers:
     - import_tasks: ../handlers/main.yml

