# EMN DevOps initializer

- name: Provision Raspberry Pi Entertainment Consoles
  hosts: raspberries
  gather_facts: true
  tasks:

    - import_role:
        name: apt
      tags: [ 'init', 'apt' ]
  
    - import_role:
        name: config
      tags: [ 'init', 'config' ]
  
    - import_role:
        name: autostart
      tags: [ 'init', 'autostart' ]
  
    - import_role:
        name: k3s
      tags: [ 'init', 'k3s' ]
      when: options.install.k3s
  
  handlers:
     - import_tasks: ../handlers/main.yml

