
- name: Provision Raspberry Pi K3S Cluster
  gather_facts: true
  hosts: all

  tasks:

    - import_role:
        name: apt
      tags: [ 'apt' ]

    - import_role:
        name: networking
      tags: [ 'networking' ]

    - import_role:
        name: fs
      tags: [ 'fs' ]
      when: fs_mounts is defined

    - import_role:
        name: nfs
      tags: [ 'nfs' ]
      when: nfs_shares is defined or nfs_mounts is defined

    - import_role:
        name: k3s
      tags: [ 'k3s' ]
      when: k3s is defined

  handlers:
     - import_tasks: ../handlers/main.yaml

