# EMN DevOps initializer

- name: Provision Raspberry Pi Entertainmet Consoles
  hosts: raspberries
  gather_facts: true
  roles:
    - { role: apt, tags: [ 'init', 'apt' ]  }
    - { role: config, tags: [ 'init', 'config' ]  }
    - { role: autostart, tags: [ 'init', 'autostart' ]  }