
- name: Provision Raspberry Pi Machines
  gather_facts: true
  hosts: all

  tasks:

    - import_role:
        name: system
      tags: [ 'system' ]

    - import_role:
        name: apt
      tags: [ 'apt' ]
  
    - import_role:
        name: configs
      tags: [ 'configs' ]

    - import_role:
        name: golang
      tags: [ 'golang' ]
      when: go is defined

    - import_role:
        name: fs
      tags: [ 'fs' ]
      when: fs_mounts is defined
    
    - import_role:
        name: repos
      tags: [ 'repos' ]
      when: repos is defined

    - import_role:
        name: nfs
      tags: [ 'nfs' ]
      when: nfs_shares is defined or nfs_mounts is defined
  
    - import_role:
        name: k3s
      tags: [ 'k3s' ]
      when: k3s is defined

  handlers:
     - import_tasks: ../handlers/main.yaml

