# vim:ft=ansible

- name: Copy Service Files to Pi
  become: true
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    mode: '0644'
  with_items:
    - "{{ services }}"

- name: Enable SystemD Services
  become: true
  systemd:
    name: "{{ item }}"
    enabled: yes
    daemon_reload: yes
  with_items:
    - "{{ services }}"